version: '3'

services:
  selenium:
    # platform: linux/x86_64
    image: selenium/standalone-chrome
    ports:
      - "4444:4444"
    volumes:
      - "/dev/shm:/dev/shm"
    container_name: selenium
    # shm_size: 2gb
    restart: unless-stopped
    networks:
      - insta-network  # Connect the selenium service to the custom network

  insta-blast:
    container_name: insta-blast
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    networks:
      - insta-network  # Connect the insta-blast service to the custom network

# Define the custom network
networks:
  insta-network:
    driver: bridge
